export const dataIsAllowed = [
  {
    id_modulo: 1,
    nombre: "administrador",
    icono: "fa fa-users",
    url: "/perfil",
    id_padre: 0,
    id_rol: 1,
    permisos: [
      {
        id_permiso: 1,
        nombre: "Crear",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 2,
        nombre: "Editar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 3,
        nombre: "Eliminar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 4,
        nombre: "Listar",
        id_modulo: 1,
        id_rol: 1,
      },
    ],
  },
  {
    id_modulo: 2,
    nombre: "bodega",
    icono: "fa fa-users",
    url: "/bodega",
    id_padre: 0,
    id_rol: 1,
    permisos: [
      {
        id_permiso: 1,
        nombre: "Crear",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 2,
        nombre: "Editar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 3,
        nombre: "Eliminar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 4,
        nombre: "Listar",
        id_modulo: 1,
        id_rol: 1,
      },
    ],
  },
  {
    id_modulo: 3,
    nombre: "usuarios",
    icono: "fa fa-users",
    url: "/usuarios",
    id_padre: 0,
    id_rol: 1,
    permisos: [
      {
        id_permiso: 1,
        nombre: "Crear",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 2,
        nombre: "Editar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 3,
        nombre: "Eliminar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 4,
        nombre: "Listar",
        id_modulo: 1,
        id_rol: 1,
      },
    ],
  },
  {
    id_modulo: 4,
    nombre: "categorias",
    icono: "fa fa-users",
    url: "/categorias",
    id_padre: 0,
    id_rol: 1,
    permisos: [
      {
        id_permiso: 1,
        nombre: "Crear",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 2,
        nombre: "Editar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 3,
        nombre: "Eliminar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 4,
        nombre: "Listar",
        id_modulo: 1,
        id_rol: 1,
      },
    ],
  },
  {
    id_modulo: 5,
    nombre: "notificaciones",
    icono: "fa fa-users",
    url: "/notificaciones",
    id_padre: 0,
    id_rol: 1,
    permisos: [
      {
        id_permiso: 1,
        nombre: "Crear",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 2,
        nombre: "Editar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 3,
        nombre: "Eliminar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 4,
        nombre: "Listar",
        id_modulo: 1,
        id_rol: 1,
      },
    ],
  },
  {
    id_modulo: 6,
    nombre: "producto",
    icono: "fa fa-users",
    url: "/producto",
    id_padre: 0,
    id_rol: 1,
    permisos: [
      {
        id_permiso: 1,
        nombre: "Crear",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 2,
        nombre: "Editar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 3,
        nombre: "Eliminar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 4,
        nombre: "Listar",
        id_modulo: 1,
        id_rol: 1,
      },
    ],
  },
  {
    id_modulo: 7,
    nombre: "proveedor",
    icono: "fa fa-users",
    url: "/proveedor",
    id_padre: 0,
    id_rol: 1,
    permisos: [
      {
        id_permiso: 1,
        nombre: "Crear",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 2,
        nombre: "Editar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 3,
        nombre: "Eliminar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 4,
        nombre: "Listar",
        id_modulo: 1,
        id_rol: 1,
      },
    ],
  },
  {
    id_modulo: 8,
    nombre: "pedidos",
    icono: "fa fa-users",
    url: "/pedidos",
    id_padre: 0,
    id_rol: 1,
    permisos: [
      {
        id_permiso: 1,
        nombre: "Crear",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 2,
        nombre: "Editar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 3,
        nombre: "Eliminar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 4,
        nombre: "Listar",
        id_modulo: 1,
        id_rol: 1,
      },
    ],
  },
  {
    id_modulo: 9,
    nombre: "analityc",
    icono: "fa fa-users",
    url: "/analityc",
    id_padre: 0,
    id_rol: 1,
    permisos: [
      {
        id_permiso: 1,
        nombre: "Crear",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 2,
        nombre: "Editar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 3,
        nombre: "Eliminar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 4,
        nombre: "Listar",
        id_modulo: 1,
        id_rol: 1,
      },
    ],
  },
  {
    id_modulo: 10,
    nombre: "perfil",
    icono: "fa fa-users",
    url: "/perfil",
    id_padre: 0,
    id_rol: 1,
    permisos: [
      {
        id_permiso: 1,
        nombre: "Crear",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 2,
        nombre: "Editar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 3,
        nombre: "Eliminar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 4,
        nombre: "Listar",
        id_modulo: 1,
        id_rol: 1,
      },
    ],
  },
  {
    id_modulo: 11,
    nombre: "dasboard",
    icono: "fa fa-users",
    url: "/dasboard",
    id_padre: 0,
    id_rol: 1,
    permisos: [
      {
        id_permiso: 1,
        nombre: "Crear",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 2,
        nombre: "Editar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 3,
        nombre: "Eliminar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 4,
        nombre: "Listar",
        id_modulo: 1,
        id_rol: 1,
      },
    ],
  },
  {
    id_modulo: 12,
    nombre: "shope",
    icono: "fa fa-users",
    url: "/shope",
    id_padre: 0,
    id_rol: 1,
    permisos: [
      {
        id_permiso: 1,
        nombre: "Crear",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 2,
        nombre: "Editar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 3,
        nombre: "Eliminar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 4,
        nombre: "Listar",
        id_modulo: 1,
        id_rol: 1,
      },
    ],
  },
  {
    id_modulo: 13,
    nombre: "config",
    icono: "fa fa-users",
    url: "/config",
    id_padre: 0,
    id_rol: 1,
    permisos: [
      {
        id_permiso: 1,
        nombre: "Crear",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 2,
        nombre: "Editar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 3,
        nombre: "Eliminar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 4,
        nombre: "Listar",
        id_modulo: 1,
        id_rol: 1,
      },
    ],
  },
  {
    id_modulo: 14,
    nombre: "ayudaAdmin",
    icono: "fa fa-users",
    url: "/ayudaAdmin",
    id_padre: 0,
    id_rol: 1,
    permisos: [
      {
        id_permiso: 1,
        nombre: "Crear",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 2,
        nombre: "Editar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 3,
        nombre: "Eliminar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 4,
        nombre: "Listar",
        id_modulo: 1,
        id_rol: 1,
      },
    ],
  },
  {
    id_modulo: 15,
    nombre: "reportes",
    icono: "fa fa-users",
    url: "/reportes",
    id_padre: 0,
    id_rol: 1,
    permisos: [
      {
        id_permiso: 1,
        nombre: "Crear",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 2,
        nombre: "Editar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 3,
        nombre: "Eliminar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 4,
        nombre: "Listar",
        id_modulo: 1,
        id_rol: 1,
      },
    ],
  },
  {
    id_modulo: 16,
    nombre: "start",
    icono: "fa fa-users",
    url: "/startAdmin",
    id_padre: 0,
    id_rol: 1,
    permisos: [
      {
        id_permiso: 1,
        nombre: "Crear",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 2,
        nombre: "Editar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 3,
        nombre: "Eliminar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 4,
        nombre: "Listar",
        id_modulo: 1,
        id_rol: 1,
      },
    ],
  },
  {
    id_modulo: 17,
    nombre: "venta",
    icono: "fa fa-users",
    url: "/venta",
    id_padre: 0,
    id_rol: 1,
    permisos: [
      {
        id_permiso: 1,
        nombre: "Crear",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 2,
        nombre: "Editar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 3,
        nombre: "Eliminar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 4,
        nombre: "Listar",
        id_modulo: 1,
        id_rol: 1,
      },
    ],
  },
  {
    id_modulo: 18,
    nombre: "inventoryGeneral",
    icono: "fa fa-users",
    url: "/inventoryGeneral",
    id_padre: 0,
    id_rol: 1,
    permisos: [
      {
        id_permiso: 1,
        nombre: "Crear",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 2,
        nombre: "Editar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 3,
        nombre: "Eliminar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 4,
        nombre: "Listar",
        id_modulo: 1,
        id_rol: 1,
      },
    ],
  },
  {
    id_modulo: 19,
    nombre: "trae",
    icono: "fa fa-users",
    url: "/trae",
    id_padre: 0,
    id_rol: 1,
    permisos: [
      {
        id_permiso: 1,
        nombre: "Crear",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 2,
        nombre: "Editar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 3,
        nombre: "Eliminar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 4,
        nombre: "Listar",
        id_modulo: 1,
        id_rol: 1,
      },
    ],
  },
  {
    id_modulo: 20,
    nombre: "LicenceSoftware/state",
    icono: "fa fa-users",
    url: "/LicenceSoftware/state",
    id_padre: 0,
    id_rol: 1,
    permisos: [
      {
        id_permiso: 1,
        nombre: "Crear",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 2,
        nombre: "Editar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 3,
        nombre: "Eliminar",
        id_modulo: 1,
        id_rol: 1,
      },
      {
        id_permiso: 4,
        nombre: "Listar",
        id_modulo: 1,
        id_rol: 1,
      },
    ],
  },
];
